CrossTab/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'RestRoom.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', RedirectView.as_view(url='/app/')),
    url(r'^app/', include('app.urls', namespace='app')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
)

app/urls.py
from django.conf.urls import patterns, url

from app.views import ClassicLogin, ClassicSignUP, Cross_tabulate, File_upload, Home, Load_old_file,\
    Login, Logout


urlpatterns = patterns('',
                       url(r'^$', Home.as_view(), name='home'),
                       url(r'^login/$', Login.as_view(), name='login'),
                       url(r'^classiclogin/$', ClassicLogin.as_view(), name='classiclogin'),
                       url(r'^logout/$', Logout.as_view(), name='logout'),
                       url(r'^home/$', Home.as_view(), name='home'),
                       url(r'^signup', ClassicSignUP.as_view(), name='signup'),
                       url(r'^upload', File_upload.as_view(), name='file_upload'),
                       url(r'^cross_tabulate', Cross_tabulate.as_view(), name='cross_tabulate'),
                       url(r'^load_old_file', Load_old_file.as_view(), name='load_old_file'),
                       )

app/templates/explore.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>RestRoom | Explore</title>

    <!-- Bootstrap core CSS -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
   <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>
   <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
   <script src="//code.jquery.com/jquery-1.10.2.js"></script>
   <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>

    <!-- Custom styles for this template -->
    <style type="text/css">

          /* Move down content because we have a fixed navbar that is 50px tall */
      body {
        padding-top: 50px;
        padding-bottom: 20px;
      }

      html, body{
        height: 100%;
        margin: 0px;
        padding: 0px
      }

        #map-canvas{
          height: 800px;
          width: 100%;
        }
      .controls {
          margin-top: 16px;
          border: 1px solid transparent;
          border-radius: 2px 0 0 2px;
          box-sizing: border-box;
          -moz-box-sizing: border-box;
          height: 32px;
          outline: none;
          box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
        }

        #pac-input {
 /*         background-color: #fff;
          padding: 0 11px 0 13px;
          width: 400px;
          font-family: Roboto;
          font-size: 15px;
          font-weight: 300;
          text-overflow: ellipsis;*/
        }

        #pac-input:focus {
          border-color: #4d90fe;
          margin-left: -1px;
          padding-left: 14px;  /* Regular padding-left + 1. */
          width: 401px;
        }

        .pac-container {
          font-family: Roboto;
        }

        #type-selector {
          color: #fff;
          background-color: #4d90fe;
          padding: 5px 11px 0px 11px;
        }

        #type-selector label {
          font-family: Roboto;
          font-size: 13px;
          font-weight: 300;
        }

      #target {
        width: 345px;
      }
    .container {
      width: 100%;
    }

    </style>

  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Hello, {{user.first_name}} {{user.last_name}}</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <!-- <input type="text" id="pac-input" class="controls"> -->
            </div>
            <img src="http://i.imgur.com/67I6mTq.gif" style="display:none" id="gif-loader">
            <img src="http://provennutritionforkids.com/wp-content/uploads/2012/10/Green-CheckMark.png" style="display:none" id="gif-done">
            <a href="{% url 'app:home' %}" class="btn btn-success" id="update-location">Home</a>
            <a href="{% url 'app:logout' %}" class="btn btn-success">Logout</a>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <div class="container">
      <!-- <input id="pac-input" class="controls" type="text" placeholder="Search Box"> -->
<!--       <input id="pac-input" class="controls" type="text" placeholder="Search Box"> -->
      <div id="map-canvas"></div>
      <p style="margin-bottom:-100px">

          <label for="amount">Explore others(50 Km increments):</label>
          <input type="text" id="amount" readonly style="border:0; color:#f6931f; font-weight:bold;">
      </p>
      <div id="slider"></div>
    </div>

    <script>

    var latitude, longitude, map, infowindows = [], markers = [];

    var data = {{data|safe}};

    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    var csrftoken = getCookie('csrftoken');

    $(document).ready(function(){


      $(function() {
        $( "#slider" ).slider({
          value: 200,
          min: 0,
          max: 20000,
          step: 50,
          slide: function( event, ui ) {
            $( "#amount" ).val(ui.value + ' KM');

            $.ajax({
            url: "{% url 'app:peoplenearby' %}",
            type: 'POST',
            data: {csrfmiddlewaretoken:csrftoken,
                   distance: ui.value
                 },
            success: function(data) {
              console.log(data);
              $('#gif-loader').hide();
              $('#gif-done').show();  
              $( "#gif-done" ).fadeOut(1000);
              if(data.status){
                putMarkers({}, JSON.parse(data.data));
              } 
              else{
                alert('Opps!!')
              }  


            },
            error: function(e) {
              console.log('error');
              console.log(e.toString());
            }
          });


          }
        });
        $( "#amount" ).val($( "#slider" ).slider( "value" ) + ' Km');
      });

    });



    function clearMarkersWindows() {
      for (var i = 0; i < markers.length; i++) {
        markers[i].setMap(null);
        infowindows[i].close();
      }
    }

    function moreinfo(marker, infowindow){

      var f = function(){
        console.log('Guess what, someone clicked me!')
        content = '<div><strong>' +  marker.custom_info.first_name + ' ' + marker.custom_info.last_name + '</strong><br>' + marker.custom_info.address + '</div>';
        infowindow.setContent(content);
        infowindow.open(map, marker);
      }
      return f;

    }

    function putMarkers(foo, loc_data){
      console.log('Running putMarkers');

      clearMarkersWindows();
      markers = [];
      infowindows = [];

      if(loc_data === undefined){
        loc_data = data;
      }

      console.log(JSON.stringify(loc_data));

      var bounds = new google.maps.LatLngBounds();

      for(var i=0; i < loc_data.length; i++){
        var loc = loc_data[i];
        var geolocate = new google.maps.LatLng(loc.lat, loc.lang);
        var marker = new google.maps.Marker({
           map: map,
           anchorPoint: new google.maps.Point(0, -29),
           title: 'Click for more info!'
        });
        marker.setPosition(geolocate);
        marker.setVisible(true);
        var infowindow = new google.maps.InfoWindow();

        marker.custom_info = {first_name: loc.first_name,
                              last_name: loc.last_name,
                              address: loc.address,
                              infowindow: infowindow
                            }
        
        //closure call
        google.maps.event.addListener(marker, 'click', moreinfo(marker, infowindow));
        
        infowindow.setContent('<div>' +  loc.first_name + '</div>');
        infowindow.open(map, marker);
        markers.push(marker); 
        infowindows.push(infowindow);
        bounds.extend(geolocate);
      }

      map.fitBounds(bounds);
      map.setCenter(bounds.getCenter());

    }


    function initialize() {

      console.log('Running initialize');

      map = new google.maps.Map(document.getElementById('map-canvas'), {
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        center: new google.maps.LatLng({{user.lat}}, {{user.lang}}),
        zoom: 14
      });
    }

    google.maps.event.addDomListener(window, 'load', initialize);
    google.maps.event.addDomListener(window, 'load', putMarkers);

    </script>

  </body>
</html>

app/templates/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>RestRoom | Home</title>

    <!-- Bootstrap core CSS -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
   <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.5.0/bootstrap-table.min.css">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
   <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.2/js/bootstrap.min.js"></script> -->
   <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.5.0/bootstrap-table.min.js"></script>
   <script src="http://gregpike.net/demos/bootstrap-file-input/bootstrap.file-input.js"></script>
      <style type="text/css">

      body {
        padding-top: 50px;
        padding-bottom: 20px;
      }

      html, body{
        height: 100%;
        margin: 0px;
        padding: 0px
      }

     .container {
        width: 100%;
      }

      .cross{
          overflow-y: scroll;
          max-height: 400px;
      }

    </style>

  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Hello, {{user.first_name}} {{user.last_name}}</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form id="file_form" class="navbar-form navbar-right" method="POST" action="{% url 'app:file_upload' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
              <!-- <input type="text" id="pac-input" class="controls"> -->
            </div>
            <img src="http://i.imgur.com/67I6mTq.gif" style="display:none" id="gif-loader">
            <img src="http://provennutritionforkids.com/wp-content/uploads/2012/10/Green-CheckMark.png" style="display:none" id="gif-done">
            <img src="http://www.band-aidbrandfirstaid.com/sites/all/themes/firstaid/images/close.gif" style="display:none" id="gif-error">
            <select class="form-control" id="old_files">
              <option>Load an older file</option>
              {% for file in old_files %}
                  <option value="{{file.uploaded_file}}">{{file.actual_name}}</option>
              {% endfor %}
            </select>
            <input type="hidden" name="userid" value="{{ user.id }}">
            <input type="file" name="uploaded_file" data-filename-placement="inside" id="browse_file">
            <!-- <input type="submit" value="Upload file" class="btn btn-success"> -->
            <!-- <a href="#" class="btn btn-success" id="upload">Upload file</a> -->
            <a href="{% url 'app:logout' %}" class="btn btn-success">Logout</a>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    <div class="container">

    <form id="ct_form" class="navbar-left form-inline" method="POST" action="{% url 'app:cross_tabulate' %}" style="display:None">
      {% csrf_token %}
      <select class="form-control" id="field1" name="field1">
      </select>

      <select class="form-control" id="field2" name="field2">
      </select>

      <input type="submit" value="Cross-tabulate" class="btn btn-success">

      </form>
      <br/>

      <div class="jumbotron" id="welcome">
        <h1>Welcome to CrossTab</h1>
        <p class="lead">Upload a <a target="_blank" href="http://en.wikipedia.org/wiki/Comma-separated_values">CSV file</a> using the "browse" button on the top right to get started.</p>
      </div>

      <div id="main_table">
      </div>
      <div id="cross_table_div">
          <h4 style="margin-left:45%">Cross tabulation results</h4>
          <div id="cross_table" class="cross"></div>
      </div>

    </div>


    <script>

    var file_name;

    if (!String.prototype.format) {
      String.prototype.format = function() {
        var args = arguments;
        return this.replace(/{(\d+)}/g, function(match, number) { 
          return typeof args[number] != 'undefined'
            ? args[number]
            : match
          ;
        });
      };
    }

    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    var main_table =  "<table id='table' data-toggle='table' data-height='400'>"+
                      "<thead>"+
                      "<tr>{0}</tr>"+
                      "</thead>"+
                      "</table>";

    function populate(id, fields, ignore){
      $(id).html('');
      var options = '';
      for(var i=0; i < fields.length; i++){
        if(fields[i] !== ignore){
          options += '<option>{0}</option>'.format(fields[i]);
        }
        
      }

      $(id).html(options);
    }

    function process_data(data){

      $('#main_table').html('');
      var rows = '';
      var ct_fields = '';
      for(var i=0; i < data.headers.length; i++){
         rows += '<th data-field="{0}">{1}</th>'.format(data.headers[i], data.headers[i]);
      }
      $('#main_table').html(main_table.format(rows));
      populate('#field1', data.headers);
      populate('#field2', data.headers.slice(1));
      console.log(main_table.format(rows));
      $('#table').bootstrapTable({
           data: data.data
      });
    }

    function success_gif(){
      $('#gif-loader').hide();
      $('#gif-done').show();  
      $("#gif-done" ).fadeOut(1000);
    }

    function failure_gif(){
      $('#gif-loader').hide();
      $('#gif-error').show();  
      $( "#gif-error" ).fadeOut(1000);
    }

    var csrftoken = getCookie('csrftoken');

    $(document).ready(function(){

      $('#cross_table_div').hide()

      $('input[type=file]').bootstrapFileInput();

      {% if headers %}
      var headers = {{headers|safe}};
      var data = {{data|safe}};
      file_name = "{{file_name}}";
      process_data({data: data, headers: headers});
      $('#welcome').hide();
      $('#ct_form').show()

      {% endif %}


      $('#field1').change(function(){
        var options = $.map($(this).find('option'), function(e) { return e.value; });
        populate('#field2', options, $(this).val());
      });

      $('#old_files').change(function(){
        $('#gif-loader').show()

        var name = $(this).val();
        $.ajax({
            url: "{% url 'app:load_old_file' %}",
            type: 'POST',
            data: {file_name: name, csrfmiddlewaretoken: csrftoken},
            success: function(data, textStatus, jqXHR)
            {

              if(data.status){
                success_gif();
                file_name = data.file_name;
                process_data({data: data.data, headers: data.headers});
                $('#cross_table_div').hide()
                $('#cross_table').html('');
                file_name = name;
              }
              else{
                failure_gif();
                alert(data.error);
              }


            },
             error: function(jqXHR, textStatus, errorThrown) 
             {
              failure_gif();
              alert('Oops! Something went wrong.')
             }          
        });

      })

      $('#ct_form').submit(function(e){

        e.preventDefault();
        console.log('Sending cross tabulation request....');

        var field1 = $('#field1').val();
        var field2 = $('#field2').val();

        console.log([field1, field2]);

        if(!(field1 && field2 && field1 != field2)){

          alert('Please choose the fields properly.');
          return false;
        }

        var form_obj = $(this);
        var form_URL = form_obj.attr("action");
        var form_data = new FormData(this);
        form_data.append('file_name', file_name);
        $('#gif-loader').show()

        $.ajax({
            url: form_URL,
            type: 'POST',
            data: form_data,
            mimeType:"multipart/form-data",
            contentType: false,
            cache: false,
            processData:false,
            success: function(data, textStatus, jqXHR)
            {
              data = JSON.parse(data);
              if(data.status){
                success_gif();
                $('#cross_table_div').show();
                $('#cross_table').html(data.data);
              }
              else{
                failure_gif();
                alert(data.error);
              }
              
            },
             error: function(jqXHR, textStatus, errorThrown) 
             {
              failure_gif();
              alert('Oops! Something went wrong.')
             }          
        });
        
      });

      $('#browse_file').change(function(){
         $('#file_form').submit();
      });

      $('#file_form').submit(function(e){

        e.preventDefault();
        console.log('Uploading file....')
        $('#gif-loader').show()

        var form_obj = $(this);
        var form_URL = form_obj.attr("action");
        var form_data = new FormData(this);
        var actual_name = $(this).find('input[type=file]').val().split('\\').pop();

        $.ajax({
            url: form_URL,
            type: 'POST',
                data: form_data,
            mimeType:"multipart/form-data",
            contentType: false,
                cache: false,
                processData:false,
            success: function(data, textStatus, jqXHR)
            {

              console.log(data);

              data = JSON.parse(data);

              if(data.status){
                success_gif();
                console.log(data);
                file_name = data.file_name;
                process_data({data: data.data, headers: data.headers});
                $('#cross_table_div').hide()
                $('#cross_table').html('');
                $("#file_form option:first").after('<option value="{0}">{1}</option>'.format(data.file_name, actual_name));
                $('#file_form option:eq(1)').prop('selected', true);
                $('#welcome').hide();
                $('#ct_form').show()
              }
              else{
                failure_gif();
                alert(data.error);
              }


            },
             error: function(jqXHR, textStatus, errorThrown) 
             {
              failure_gif();
              alert("Oops! Something went wrong.")
             }          
        });
        
      });

    });

    </script>

  </body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>RestRoom Login</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
<!-- /*    <style type="text/css">
        .col-md-offset-3 {
            margin: 20% auto !important;
            float: none;
        }
    </style>*/ -->
  </head>

  <body>

    <div class="container">    
        <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">                    
            <div class="panel panel-info" >
                    <div class="panel-heading">
                        <div class="panel-title">Sign In</div>
                        <div style="float:right; font-size: 80%; position: relative; top:-10px"><a href="#">Forgot password?</a></div>
                    </div>     

                    <div style="padding-top:30px" class="panel-body" >

                        <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
                            
                        <form id="loginform" class="form-horizontal" role="form" action="{% url 'app:classiclogin' %}" method="POST">
                        {% csrf_token %} 
                                    
                            <div style="margin-bottom: 25px" class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                        <input id="login-username" type="text" class="form-control" name="email" value="" placeholder="email">                                        
                                    </div>
                                
                            <div style="margin-bottom: 25px" class="input-group">
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                        <input id="login-password" type="password" class="form-control" name="password" placeholder="password">
                                    </div>
                                    
                                <div style="margin-top:10px" class="form-group">
                                    <!-- Button -->

                                    <div class="col-sm-12 controls">
                                      <input type="submit" class="btn btn-success" value="Login">
                                      <a id="btn-fblogin" href="{% url 'social:begin' 'facebook' %}?next={%url 'app:home' %}" class="btn btn-primary">Login with Facebook</a>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-12 control">
                                        <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                                            Don't have an account! 
                                        <a href="#" onClick="$('#loginbox').hide(); $('#signupbox').show()">
                                            Sign Up Here
                                        </a>
                                        </div>
                                    </div>
                                </div>    
                            </form>     

                        </div>                     
                    </div>  
        </div>
        <div id="signupbox" style="display:none; margin-top:50px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <div class="panel-title">Sign Up</div>
                            <div style="float:right; font-size: 85%; position: relative; top:-10px"><a id="signinlink" href="#" onclick="$('#signupbox').hide(); $('#loginbox').show()">Sign In</a></div>
                        </div>  
                        <div class="panel-body" >
                            <form id="signupform" class="form-horizontal" role="form" action="{% url 'app:signup'%}" method="POST">
                            {% csrf_token %}
                                
                                <div id="signupalert" style="display:none" class="alert alert-danger">
                                    <p>Error:</p>
                                    <span></span>
                                </div>
                                  
                                <div class="form-group">
                                    <label for="email" class="col-md-3 control-label">Email</label>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control" name="email" placeholder="Email Address">
                                    </div>
                                </div>
                                    
                                <div class="form-group">
                                    <label for="firstname" class="col-md-3 control-label">First Name</label>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control" name="first_name" placeholder="First Name">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="lastname" class="col-md-3 control-label">Last Name</label>
                                    <div class="col-md-9">
                                        <input type="text" class="form-control" name="last_name" placeholder="Last Name">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="password" class="col-md-3 control-label">Password</label>
                                    <div class="col-md-9">
                                        <input type="password" class="form-control" name="password" placeholder="Password">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <!-- Button -->                                        
                                    <div class="col-md-offset-3 col-md-9">
                                        <input type="submit" class="btn btn-info"><i class="icon-hand-right" value="Sign Up">
<!--                                         <span style="margin-left:8px;">or</span> -->  
                                    </div>
                                </div>
<!--                                 
                                <div style="border-top: 1px solid #999; padding-top:20px"  class="form-group">
                                    
                                    <div class="col-md-offset-3 col-md-9">
                                        <a href="{% url 'social:begin' 'facebook' %}?next={%url 'app:home' %}" id="btn-fbsignup" class="btn btn-primary"><i class="icon-facebook"></i>Sign Up with Facebook</a>
                                    </div>                                           
                                        
                                </div> -->
                                
                                
                                
                            </form>
                         </div>
                    </div>

               
               
                
         </div> 
    </div>






    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
  </body>
</html>